# THIS FILE IS AUTOMATICALLY GENERATED
# Project: G:\Psoc4_prj\7.rental_house\18-04-11\second_images[4-9]\EntranceGuard_171019-12.50\BLE_OTA_External_Memory_Bootloader01.cydsn\BLE_OTA_External_Memory_Bootloader01.cyprj
# Date: Mon, 23 Apr 2018 08:28:36 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 31.25 -waveform {0 15.625} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 31.25 -waveform {0 15.625} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 31.25 -waveform {0 15.625} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 62.5 -waveform {0 15.625} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for G:\Psoc4_prj\7.rental_house\18-04-11\second_images[4-9]\EntranceGuard_171019-12.50\BLE_OTA_External_Memory_Bootloader01.cydsn\TopDesign\TopDesign.cysch
# Project: G:\Psoc4_prj\7.rental_house\18-04-11\second_images[4-9]\EntranceGuard_171019-12.50\BLE_OTA_External_Memory_Bootloader01.cydsn\BLE_OTA_External_Memory_Bootloader01.cyprj
# Date: Mon, 23 Apr 2018 08:28:31 GMT
